### ISSUE TITLE
Getting raw data?

### ISSUE THREAD

**Issue by randesu** [nup002/PhoneSensors#3]
Hello, what code snippet should I use to get raw data from my phone before it's ended up in an array?

**Comment by nup002** [comment]
To get the raw readings from your phone without parsing the data into arrays first, define a custom parser that just returns the same data as it receives. Example:

```
from phonesensors import SensorStreamerClient

my_parser= lambda raw_data: raw_data
with SensorStreamerClient("192.168.1.2", 5000, custom_parser=my_parser) as client:
  for data in client:
    print(data)
```
